# Change these first
owner: small-big-wedding # Your GitHub organization or username, where this repository lives
repo: uptime-checker # The name of this repository

sites:
  - name: SmallBigWedding
    url: https://www.smallbigwedding.kr/

status-website:
  baseUrl: /uptime-checker
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Uptime Checker
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
  metaTags:
    - name: "robots"
      content: "noindex" 

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
